import streamlit as st
from openai import OpenAI
from PIL import Image
import os, base64, requests, json
from io import BytesIO
from dotenv import load_dotenv

# --- 1. CONFIG ---
st.set_page_config(page_title="GEM >3 Auto-Pilot", layout="centered")

# --- 2. THE "BEST FREE" PRIORITY LISTS (2026 Edition) ---
# We prioritize speed and context window for text, and vision capabilities for images.
FREE_TEXT_MODELS = [
    "google/gemini-2.0-flash-lite:preview:free", 
    "meta-llama/llama-3.3-70b-instruct:free",
    "mistralai/mistral-small-24b-instruct-2501:free"
]

FREE_VISION_MODELS = [
    "google/gemini-2.0-flash-lite:preview:free",
    "nvidia/llama-3.2-11b-vision-instruct:free",
    "qwen/qwen-2-vl-7b-instruct:free"
]

# --- 3. SESSION INITIALIZATION ---
if "messages" not in st.session_state: st.session_state.messages = []
if "active_model" not in st.session_state: st.session_state.active_model = FREE_TEXT_MODELS[0]

# --- 4. CORE HELPERS ---
def encode_image(img):
    img = img.convert("RGB")
    buf = BytesIO()
    img.save(buf, format="JPEG")
    return base64.b64encode(buf.getvalue()).decode('utf-8')

# --- 5. AUTH & CLIENT ---
load_dotenv()
api_key = os.getenv("OPENROUTER_API_KEY") or st.secrets.get("OPENROUTER_API_KEY")
client = OpenAI(base_url="https://openrouter.ai/api/v1", api_key=api_key)

with st.sidebar:
    st.title("🚀 Auto-Pilot Mode")
    st.info("The system will automatically switch to the best available free model.")
    
    st.divider()
    uploaded_file = st.file_uploader("🖼️ Attach Image", type=["jpg", "png", "jpeg"])
    
    if st.button("🗑️ Clear Chat"):
        st.session_state.messages = []
        st.rerun()

# --- 6. CHAT DISPLAY ---
for m in st.session_state.messages:
    with st.chat_message(m["role"]):
        if "image_b64" in m:
            st.image(f"data:image/jpeg;base64,{m['image_b64']}", use_container_width=True)
        st.markdown(m["content"])

# --- 7. THE SMART-SWITCH LOGIC ---
if prompt := st.chat_input("Message GEM >3..."):
    user_msg = {"role": "user", "content": prompt}
    is_vision_task = False
    
    if uploaded_file:
        user_msg["image_b64"] = encode_image(Image.open(uploaded_file))
        is_vision_task = True
    
    st.session_state.messages.append(user_msg)
    
    with st.chat_message("user"):
        if is_vision_task:
            st.image(f"data:image/jpeg;base64,{user_msg['image_b64']}", use_container_width=True)
        st.markdown(prompt)

    with st.chat_message("assistant"):
        # Select the correct priority list
        priority_list = FREE_VISION_MODELS if is_vision_task else FREE_TEXT_MODELS
        
        # Build API history
        api_messages = []
        for m in st.session_state.messages:
            if "image_b64" in m:
                api_messages.append({
                    "role": m["role"],
                    "content": [
                        {"type": "text", "text": m["content"]},
                        {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{m['image_b64']}"}}
                    ]
                })
            else:
                api_messages.append({"role": m["role"], "content": m["content"]})

        # FALLBACK EXECUTION: Try models in order until one works
        def stream_with_fallback():
            for model_id in priority_list:
                try:
                    # Log which model we are trying
                    # st.caption(f"Attempting: {model_id}...") 
                    
                    stream = client.chat.completions.create(
                        model=model_id,
                        messages=api_messages,
                        stream=True,
                        # OpenRouter specific: tells it to try other models if this one fails
                        extra_body={"models": priority_list} 
                    )
                    
                    full_text = ""
                    for chunk in stream:
                        if chunk.choices and chunk.choices[0].delta.content:
                            content = chunk.choices[0].delta.content
                            full_text += content
                            yield content
                    
                    # If we reach here, the model successfully finished
                    st.session_state.active_model = model_id
                    return 
                    
                except Exception as e:
                    continue # Try the next model in the list
            
            yield "❌ All free models are currently offline or rate-limited. Please try again in a moment."

        full_res = st.write_stream(stream_with_fallback())
        st.session_state.messages.append({"role": "assistant", "content": full_res})
        st.caption(f"Response generated by: `{st.session_state.active_model}`")
